#!/usr/bin/env node
/* ==========================================================================
   WayMaker Ink — local dev server for the booking form
   No dependencies. Node 18+.

     node dev-server.js                 # uses public/config.js as-is
     WM_ARTISTS='{"laynie":{"enabled":true,"name":"Laynie Joy"}}' node dev-server.js

   Stands in for nginx well enough to develop against:
     · try_files $uri $uri/ /index.html   — so /nic and /laynie resolve
     · /healthz                           — same 200 'ok'
     · config.js generated by the REAL docker-entrypoint.sh when env vars are
       set, so what you test is the code path that ships

   It is NOT nginx. Caching headers, gzip and the security headers from
   nginx.conf are not reproduced — verify those against the container.
   ========================================================================== */
'use strict';

const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, 'public');
const PORT = Number(process.env.PORT) || 8080;

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon'
};

/* Run the shipping entrypoint against a temp target rather than duplicating
   its logic here — and never against public/config.js, which is the tracked
   local-dev fallback. */
let generatedConfig = null;

if (process.env.WM_WEBHOOK_URL || process.env.WEBHOOK_URL || process.env.WM_ARTISTS) {
  const tmp = path.join(os.tmpdir(), 'wm-config-' + process.pid + '.js');
  try {
    const out = execFileSync('sh', [path.join(__dirname, 'docker-entrypoint.sh')], {
      env: { ...process.env, WM_CONFIG_TARGET: tmp },
      encoding: 'utf8'
    });
    process.stdout.write(out);
    generatedConfig = fs.readFileSync(tmp, 'utf8');
    fs.unlinkSync(tmp);
    console.log('[dev] serving generated config.js (env vars detected)');
  } catch (err) {
    console.error('[dev] docker-entrypoint.sh failed:', err.message);
    console.error('[dev] falling back to the committed public/config.js');
  }
} else {
  console.log('[dev] no WM_* env set — serving the committed public/config.js');
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, 'http://localhost');
  const pathname = decodeURIComponent(url.pathname);

  if (pathname === '/healthz') {
    res.writeHead(200, { 'Content-Type': 'text/plain' });
    return res.end('ok');
  }

  if (pathname === '/config.js' && generatedConfig !== null) {
    res.writeHead(200, { 'Content-Type': TYPES['.js'], 'Cache-Control': 'no-store' });
    return res.end(generatedConfig);
  }

  /* try_files $uri $uri/ /index.html — a real file wins, anything else falls
     through to the app so client-side routing sees the path. */
  const candidate = path.join(ROOT, pathname);
  const resolved = path.resolve(candidate);
  if (!resolved.startsWith(path.resolve(ROOT))) {
    res.writeHead(403).end('forbidden');
    return;
  }

  let file = null;
  if (fs.existsSync(resolved) && fs.statSync(resolved).isFile()) {
    file = resolved;
  } else if (fs.existsSync(path.join(resolved, 'index.html'))) {
    file = path.join(resolved, 'index.html');
  } else {
    file = path.join(ROOT, 'index.html');
  }

  const type = TYPES[path.extname(file).toLowerCase()] || 'application/octet-stream';
  const headers = { 'Content-Type': type };
  if (file.endsWith('index.html')) headers['Cache-Control'] = 'no-store';

  res.writeHead(200, headers);
  fs.createReadStream(file).pipe(res);
});

server.listen(PORT, () => {
  console.log(`\n[dev] http://localhost:${PORT}/`);
  console.log(`[dev]   /nic      Nic's form`);
  console.log(`[dev]   /laynie   disabled unless WM_ARTISTS enables her`);
  console.log(`[dev]   /healthz  liveness\n`);
});
